name: cf workers

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      # Kita hapus cache lama agar tidak ada konflik versi worker-build
      - name: Clean Previous Builds
        run: |
          rm -rf build
          rm -rf target

      - name: Install latest worker-build
        run: cargo install worker-build

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '3.107.3'
